### ISSUE TITLE
PubInfo header_stamp is filled even when the main message has no header stamp

### ISSUE THREAD

**Issue by y-okumura-isp** [tier4/TILDE#11]
version: 3260cb
How to reproduce: Run tilde_sample.

Here is the PubInfo.
This node relays std_msgs::msg::String.

```
header:
  stamp:
    sec: 1646034075
    nanosec: 142661059
  frame_id: ''
output_info:
  topic_name: /relay_without_stamp
  node_fqn: ''
  seq: 13
  pub_time:
    sec: 1646034075
    nanosec: 142667675
  pub_time_steady:
    sec: 6846520
    nanosec: 913127491
  header_stamp:                      # std_msgs::msg::String has no header.stamp but this field is filled
    sec: 1646034075
    nanosec: 142651785
input_infos:
- topic_name: /topic_without_stamp
  sub_time:
    sec: 1646034075
    nanosec: 131743819
  sub_time_steady:
    sec: 6846520
    nanosec: 902204465
  has_header_stamp: false      # false, that's right
  header_stamp:
    sec: 0
    nanosec: 0
```
